
# Post \#75495800 [Link](https://stackoverflow.com/questions/75495800/)

## Error: Unable to extract uploader id - Youtube, Discord.py

**Vote**: 21 (256/702) **Views**: 14742 (360/702) 

**Internal ID** \#1-3-243

Created at 2023-02-18 19:19:23

Tags: `python` `ffmpeg` `discord` `youtube-dl`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I have a veary powerfull bot in discord (discord.py, PYTHON) and it can play music in voice channels. It gets the music from youtube (youtube_dl). It  but now it dosn't wanna work with any video.
I tried updataing youtube_dl but it still dosn't work
I searched everywhere but I still can't find a answer that might help me.
This is the Error: `Error: Unable to extract uploader id`
After and before the error log there is no more information.
Can anyone help?
I will leave some of the code that I use for my bot...
The youtube settup settings:
```
youtube_dl.utils.bug_reports_message = lambda: ''


ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': False,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0',  # bind to ipv4 since ipv6 addresses cause issues sometimes
}

ffmpeg_options = {
    'options': '-vn',
}

ytdl = youtube_dl.YoutubeDL(ytdl_format_options)


class YTDLSource(discord.PCMVolumeTransformer):
    def __init__(self, source, *, data, volume=0.5):
        super().__init__(source, volume)

        self.data = data

        self.title = data.get('title')
        self.url = data.get('url')
        self.duration = data.get('duration')
        self.image = data.get("thumbnails")[0]["url"]
    @classmethod
    async def from_url(cls, url, *, loop=None, stream=False):
        loop = loop or asyncio.get_event_loop()
        data = await loop.run_in_executor(None, lambda: ytdl.extract_info(url, download=not stream))
        #print(data)

        if 'entries' in data:
            # take first item from a playlist
            data = data['entries'][0]
        #print(data["thumbnails"][0]["url"])
        #print(data["duration"])
        filename = data['url'] if stream else ytdl.prepare_filename(data)
        return cls(discord.FFmpegPCMAudio(filename, **ffmpeg_options), data=data)
```

Aproximately the command to run the audio (from my bot):
```
sessionChanel = message.author.voice.channel
await sessionChannel.connect()
url = matched.group(1)
player = await YTDLSource.from_url(url, loop=client.loop, stream=True)
sessionChannel.guild.voice_client.play(player, after=lambda e: print(
                                       f'Player error: {e}') if e else None)
```



----------
        
## GPT3.5 Attempt \#0

The error message you are receiving indicates that youtube_dl is unable to extract the uploader id from the video. This could be caused by a change in the structure of the video's metadata on YouTube, or it could be a bug in youtube_dl.

One thing you can try is to update youtube_dl to the latest version. You can do this by running the following command in your terminal:

```
pip install --upgrade youtube_dl
```

If updating youtube_dl does not solve the problem, you can try passing the `--verbose` flag to youtube_dl when you extract the video information. This will give you more detailed information about what youtube_dl is doing and may help you identify the problem.

To pass the `--verbose` flag, you can modify the `ytdl_format_options` dictionary like this:

```
ytdl_format_options = {
    'format': 'bestaudio/best',
    'outtmpl': '%(extractor)s-%(id)s-%(title)s.%(ext)s',
    'restrictfilenames': True,
    'noplaylist': True,
    'nocheckcertificate': True,
    'ignoreerrors': False,
    'logtostderr': False,
    'quiet': True,
    'no_warnings': True,
    'default_search': 'auto',
    'source_address': '0.0.0.0',  # bind to ipv4 since ipv6 addresses cause issues sometimes
    'verbose': True,  # add this line to enable verbose logging
}
```

With verbose logging enabled, you should be able to see more detailed information about what youtube_dl is doing and where it is encountering the error.

If you are still unable to solve the problem, you may need to reach out to the developers of youtube_dl for assistance. They may be able to provide more information about the error and help you find a solution.

--------

## GPT3.5 Attempt \#1

The error message you are getting indicates that there is an issue with the extraction of the uploader ID from the YouTube video. This could be caused by changes to the YouTube API or the video itself.

One possible solution is to update your youtube-dl library to the latest version. You can do this by running the following command in your terminal:

```
pip install --upgrade youtube-dl
```

If this does not solve the issue, you can try adding the `--no-cache-dir` option to the command to ensure that the latest version is downloaded.

Another possible solution is to use a different library for downloading YouTube videos, such as `pytube`. You can install it using the following command:

```
pip install pytube
```

Then, you can modify your code to use `pytube` instead of `youtube_dl`. Here is an example:

```
from pytube import YouTube

class YTDLSource(discord.PCMVolumeTransformer):
    def __init__(self, source, *, data, volume=0.5):
        super().__init__(source, volume)

        self.data = data

        self.title = data.get('title')
        self.url = data.get('url')
        self.duration = data.get('duration')
        self.image = data.get("thumbnails")[0]["url"]

    @classmethod
    async def from_url(cls, url, *, loop=None, stream=False):
        loop = loop or asyncio.get_event_loop()
        yt = YouTube(url)
        yt.streams.filter(only_audio=True).first().download()
        filename = yt.default_filename
        return cls(discord.FFmpegPCMAudio(filename, **ffmpeg_options), data=yt)
```

This code uses `pytube` to download the audio stream of the YouTube video and save it to a file. Then, it uses `discord.FFmpegPCMAudio` to load the audio file and play it in the voice channel.

I hope this helps! Let me know if you have any further questions.

--------

## GPT3.5 Attempt \#2

The error message you are receiving indicates that there is an issue with the extraction of the uploader ID from the video. This could be caused by changes to the YouTube API or a bug in the youtube_dl library.

One thing you can try is to update your youtube_dl library to the latest version. You can do this by running the following command in your terminal:

```
pip install --upgrade youtube_dl
```

If updating the library does not solve the issue, you can try passing the `--no-cache-dir` flag when installing the library to ensure that any cached files are not causing the issue:

```
pip install --upgrade --no-cache-dir youtube_dl
```

If neither of these solutions work, you may need to wait for a new update to the youtube_dl library that addresses the issue. In the meantime, you can try using a different library for downloading YouTube videos, such as pytube.

--------
