
# Post \#61235853 [Link](https://stackoverflow.com/questions/61235853/)

## How to invoke Cloud Function from Cloud Scheduler with Authentication

**Vote**: 16 (306/702) **Views**: 9887 (417/702) 

**Internal ID** \#1-3-246

Created at 2020-04-15 18:19:31

Tags: `python` `authentication` `google-cloud-functions` `google-cloud-scheduler`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

I've looked everywhere and it seems people either use pubsub, app engine http or http with no auth. Not too many people out there showing their work for accessing functions via authentication w/ oidc tokens to access google functions. 

I checked out: [Cannot invoke Google Cloud Function from GCP Scheduler](https://stackoverflow.com/questions/60055422/cannot-invoke-google-cloud-function-from-gcp-scheduler) but nothing seemed to work.

Documentation I followed:
[https://cloud.google.com/scheduler/docs/http-target-auth#using-gcloud_1](https://cloud.google.com/scheduler/docs/http-target-auth#using-gcloud_1)


1. created a new service account
2. set roles (Cloud scheduler service agent/Cloud functions service agent/Cloud scheduler admin/cloud functions invoker...even tried owner!)
3. deployed google function that doesn't allow public (unauthenticated) access (a simple helloworld function)
4. setup cron job on cloud scheduler to run every minute against the new deployed function with this configuration: url = helloworld function oidc-token newly created service account audience set to hello world function url



outcome on cloud scheduler logs:

```
Expand all | Collapse all{
 httpRequest: {
 }
 insertId: "ibboa4fg7l1s9"  
 jsonPayload: {
  @type: "type.googleapis.com/google.cloud.scheduler.logging.AttemptFinished"   
  jobName: "projects/project/locations/region/jobs/tester"   
  status: "PERMISSION_DENIED"   
  targetType: "HTTP"   
  url: "https://region-project.cloudfunctions.net/tester"   
 }
 logName: "projects/project/logs/cloudscheduler.googleapis.com%2Fexecutions"  
 receiveTimestamp: "2020-04-15T17:50:14.287689800Z"  
 resource: {â€¦}  
 severity: "ERROR"  
 timestamp: "2020-04-15T17:50:14.287689800Z"
```


I saw one solution that showed someone creating a new project to get to this to work, are there any others??

Appreciate any help provided.



[New Google Function - running in central (same as my app engine app)](https://i.stack.imgur.com/8ZRRI.png)

[New Service Account - w/ Owner role](https://i.stack.imgur.com/30vXE.png)

[New Scheduled Task - Info](https://i.stack.imgur.com/1Qtr3.png)

[New Scheduled Task - Status](https://i.stack.imgur.com/60cRd.png)

[New Scheduled Task - Logs](https://i.stack.imgur.com/2tXjp.png)



If you're missing the cloudscheduler service account (ex:
service-1231231231412@gcp-sa-cloudscheduler.iam.gserviceaccount.com)
Http auth tasks wont work.
To fix, I had to disable api and renable and it gave me the service account,
I didnt use this service account but, that was the only changing factor after I did this to make it work.


----------
        
## GPT3.5 Attempt \#0

It seems like you have followed the correct steps to authenticate your Cloud Scheduler job with an OIDC token. However, the error message suggests that the service account used by Cloud Scheduler does not have the necessary permissions to invoke the Cloud Function.

Here are a few things you can try:

1. Make sure that the service account used by Cloud Scheduler has the Cloud Functions Invoker role on the Cloud Function you are trying to invoke. You can do this by going to the Cloud Function's Permissions tab and adding the service account with the Cloud Functions Invoker role.

2. Double-check that the audience parameter in your Cloud Scheduler job is set to the correct URL of the Cloud Function you are trying to invoke. This should be the URL of the Cloud Function without any query parameters or path parameters.

3. Try invoking the Cloud Function directly using the gcloud command-line tool with the same service account and OIDC token. This can help you isolate the issue and determine whether it is related to Cloud Scheduler or the Cloud Function itself.

4. If none of the above steps work, you can try creating a new project and repeating the steps to see if that resolves the issue. It's possible that there is some configuration issue in your current project that is causing the problem.

I hope this helps! Let me know if you have any further questions.

--------

## GPT3.5 Attempt \#1

It looks like you have followed the correct steps to set up authentication for your Cloud Scheduler job to access your Cloud Function. However, the error message you received indicates that the job does not have the necessary permissions to access the function.

One thing to check is whether the Cloud Scheduler service account has the necessary permissions to invoke the Cloud Function. You can check this by going to the IAM & Admin section of the Cloud Console and searching for the service account named "service-[PROJECT_NUMBER]@gcp-sa-cloudscheduler.iam.gserviceaccount.com". Make sure that this service account has the "Cloud Functions Invoker" role.

Another thing to check is whether the audience parameter in your Cloud Scheduler job is set correctly. The audience parameter should be set to the URL of your Cloud Function. Make sure that the URL is correct and that it matches the URL of your deployed function.

If you have already checked these things and are still experiencing issues, you may want to try creating a new project and setting up the Cloud Scheduler job and Cloud Function in that project. This can sometimes help to isolate and resolve issues with permissions and authentication.

I hope this helps! Let me know if you have any further questions.

--------

## GPT3.5 Attempt \#2

It seems like you have followed the correct steps to configure authentication with OIDC tokens to access Google Cloud Functions. However, the error message you received indicates that the permission was denied. 

One thing to check is whether the Cloud Scheduler service account has the necessary permissions to invoke the Cloud Function. You can check this by going to the Cloud Function's IAM page and adding the Cloud Scheduler service account with the Cloud Functions Invoker role.

Another thing to check is whether the audience parameter in the Cloud Scheduler job is set correctly. The audience parameter should be set to the URL of the Cloud Function you want to invoke.

If neither of these solutions work, you may want to try creating a new project and following the same steps to see if that resolves the issue. It's possible that there may be some configuration issue with your current project.

Lastly, it's worth noting that the Cloud Scheduler service account may take some time to propagate the necessary permissions and roles. So, you may want to wait a few minutes after making any changes before testing again.

I hope this helps! Let me know if you have any further questions.

--------
