
# Post \#65438156 [Link](https://stackoverflow.com/questions/65438156/)

## Tensorflow Keras error: Unknown image file format. One of JPEG, PNG, GIF, BMP required

**Vote**: 8 (428/702) **Views**: 10410 (411/702) 

**Internal ID** \#1-3-296

Created at 2020-12-24 12:12:25

Tags: `python` `image` `tensorflow` `keras` `google-colaboratory`

----------

#### Metadata:

Area: `Data Science & Machine Learning`

Language: `python` (full parsed tag list: `python`)

----------

**Notepad**


----------

i'm training a classifier and i made sure all the pictures are jpg but still, this error occurs:
InvalidArgumentError:  Unknown image file format. One of JPEG, PNG, GIF, BMP required.
[[{{node decode_image/DecodeImage}}]]
[[IteratorGetNext]] [Op:__inference_train_function_1481]
i tried training on a smaller dataset and also they were all jpg and there was no problem
this is the code:
```
import numpy as np
import tensorflow as tf
from tensorflow import keras

dataset = keras.preprocessing.image_dataset_from_directory(
  '/content/drive/MyDrive/fi_dataset/train', batch_size=64, image_size=(200, 200))

dense = keras.layers.Dense(units=16)
inputs = keras.Input(shape=(None, None, 3))

from tensorflow.keras import layers

x = CenterCrop(height=150, width=150)(inputs)
x = Rescaling(scale=1.0 / 255)(x)

x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = layers.MaxPooling2D(pool_size=(3, 3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)
x = layers.MaxPooling2D(pool_size=(3, 3))(x)
x = layers.Conv2D(filters=32, kernel_size=(3, 3), activation="relu")(x)

x = layers.GlobalAveragePooling2D()(x)

num_classes = 1
outputs = layers.Dense(num_classes, activation="sigmoid")(x)

model = keras.Model(inputs=inputs, outputs=outputs)

data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")
processed_data = model(data)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
               metrics=[keras.metrics.binary_accuracy],)

history=model.fit(dataset, epochs=10)
```



----------
        
## GPT3.5 Attempt \#0

The error message suggests that some of the images in your dataset are not in the expected format (JPEG, PNG, GIF, BMP). You can try to identify the problematic images by printing out their filenames and checking their file extensions. 

You can use the following code to print out the filenames of the images that are causing the error:

```
import os

for root, dirs, files in os.walk('/content/drive/MyDrive/fi_dataset/train'):
    for file in files:
        if file.endswith('.jpg'):
            try:
                img = keras.preprocessing.image.load_img(os.path.join(root, file))
                keras.preprocessing.image.img_to_array(img)
            except Exception as e:
                print(f"Error processing {os.path.join(root, file)}: {e}")
```

This code will try to load each image in the dataset and convert it to a NumPy array. If an error occurs, it will print out the filename and the error message.

Once you have identified the problematic images, you can either remove them from the dataset or convert them to the expected format using a tool like ImageMagick or Pillow.

--------

## GPT3.5 Attempt \#1

It seems like some of the images in your dataset are not in the expected format (JPEG, PNG, GIF, BMP). You can try to use the `tf.io.decode_image` function to decode the images and specify the expected image format as an argument. Here's an example:

```
def decode_image(image):
    image = tf.image.decode_jpeg(image, channels=3)
    return image

dataset = keras.preprocessing.image_dataset_from_directory(
  '/content/drive/MyDrive/fi_dataset/train', 
  batch_size=64, 
  image_size=(200, 200),
  label_mode='binary',
  preprocessing_function=decode_image)
```

In this example, the `decode_image` function is used as a preprocessing function to decode the images in the dataset. The `tf.image.decode_jpeg` function is used to decode the images in JPEG format. You can replace this with `tf.image.decode_png`, `tf.image.decode_gif`, or `tf.image.decode_bmp` depending on the expected format of your images.

Also, make sure that the file extensions of all the images in your dataset match the actual image format.

--------

## GPT3.5 Attempt \#2

The error message suggests that some of the images in your dataset are not in the expected format (JPEG, PNG, GIF, BMP). You can try to identify the problematic images by iterating over the dataset and checking the file format of each image. Here's an example code snippet that you can use:

```
import os
from PIL import Image

image_dir = '/content/drive/MyDrive/fi_dataset/train'
for subdir, dirs, files in os.walk(image_dir):
    for file in files:
        filepath = os.path.join(subdir, file)
        try:
            with Image.open(filepath) as img:
                img.verify()
        except (IOError, SyntaxError) as e:
            print(f'Invalid image file: {filepath}')
```

This code iterates over all the files in the `image_dir` directory and its subdirectories, and tries to open each file as an image using the PIL library. If the file is not a valid image file, an exception is raised and the file path is printed.

Once you identify the problematic images, you can either remove them from the dataset or convert them to the expected format using a tool like ImageMagick or Pillow.

--------
